image: registry.52tt.com/frontend/registry/docker-service/npm-publish:latest

stages:
  - publish
  - unpublish

#变量
variables:
  TT_NPM_REGISTRY: https://npm.52tt.com /ttnpm/
  TT_NPM_REGISTRY_LOGIN: https://npm.52tt.com /ttnpm

before_script:
  - npm-cli-login -r $TT_NPM_REGISTRY_LOGIN -u gitlab-ci-token -p $CI_JOB_TOKEN -e gitlab-ci@52tt.com
  - npm config set registry $TT_NPM_REGISTRY

after_script:
  - npm logout

#发布包
publish:
  stage: publish
  script:
    #发布包
    - npm publish
  environment:
    name: package-detail
    url: $TT_NPM_REGISTRY_LOGIN/-/web/detail/@tt/$CI_PROJECT_NAME
  when: manual
  only:
    - master
  tags:
    - manager

#撤销发布
unpublish:
  stage: unpublish
  script:
    #撤销发布包
    - npm unpublish --force
  when: manual
  only:
    - master
  tags:
    - manager